apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: seminario-app
  name: seminario-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seminario-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seminario-app
    spec:
      containers:
      - image: nyrha/seminario-devops-app:latest
        name: seminario-devops-app
        resources: {}
status: {}
